language: node_js

node_js:
  - node

services:
  - postgresql

install:
  - npm install

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER william WITH PASSWORD 'postgres';" -U postgres
  - npm run createTables

script: 
  - yarn test

after_success:
  - yarn coveralls