language: node_js

node_js:
  - node

services:
  - postgresql

install:
  - npm install

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER william WITH PASSWORD 'postgres';" -U postgres
  - npm run createTables
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build 

script: 
  - yarn test

after_success:
  - yarn coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
